namespace InfoTrack.GoogleRank.Services;

public class HardCodedHtmlScraper : IHtmlScraper
{
    public Task<IndexedUrl[]> SelectElementsWithCssSelector(Stream stream, ILogger logger)
    {
        return Task.FromResult(new[]
        {
            new IndexedUrl(0, "www.infotrack.com"), // i might be looking at wrong results if infotrack isn't found... but well here it is right where it should be
            new IndexedUrl(1, "https://imanage.com/partner-products/partner-product/?productId=481"),
            new IndexedUrl(2, "http://efile.illinoiscourts.gov/service-providers.htm"),
            new IndexedUrl(3, "https://www.leap.us/integrations/e-filing-infotrack/"),
            new IndexedUrl(4, "https://www.gsccca.org/learn/efiling-information/vendor-integration"),
            new IndexedUrl(5, "https://www.jbits.courts.state.co.us/efiling/web/login.htm"),
            new IndexedUrl(6, "/search?num=100&sxsrf=ALiCzsZljppeRSXkLdyF3ib_x3S0HPwGIw:1661778798894&q=efiling+%22integration%22&sa=X&ved=2ahUKEwjaiYO4kOz5AhVDkYkEHZJyDRIQ5t4CegUIzwEQAQ"),
            new IndexedUrl(7, "https://www.efiletexas.gov/Service-Providers/1eFile.htm"),
            new IndexedUrl(8, "https://www.clio.com/app-directory/infotrack/"),
            new IndexedUrl(9, "https://www.cms.gov/Regulations-and-Guidance/Review-Boards/PRRBReview/Electronic-Filing"),
            new IndexedUrl(10, "https://www.onelegal.com/blog/defining-integrated-efiling-the-next-phase-of-innovation/"),
            new IndexedUrl(11, "https://www.wipo.int/madrid/en/how_to/efile/"),
            new IndexedUrl(12, "https://efile.dol.gov/"),
            new IndexedUrl(13, "https://uslegalpro.com/pg/court-efiling-automation"),
            new IndexedUrl(14, "https://www.smokeball.com/features/legal-efiling-electronic-signatures/"),
            new IndexedUrl(15, "https://www.mncourts.gov/mncourtsgov/media/IntegrationServices/IntegratedeFilingServicesFastFacts.pdf"),
            new IndexedUrl(16, "https://www.courts.ca.gov/partners/techoverview.htm"),
            new IndexedUrl(17, "https://www.efilingportal.com/"),
            new IndexedUrl(18, "https://www.tax1099.com/integrations"),
            new IndexedUrl(19, "https://www.in.gov/courts/efiling/how-it-works/"),
            new IndexedUrl(20, "https://www.hidalgocounty.us/208/e-Filing"),
            new IndexedUrl(21, "https://mixnet.com/e-recording-and-efiling-integration-with-land-records-indexing-management/"),
            new IndexedUrl(22, "https://www.uscourts.gov/court-records/electronic-filing-cmecf"),
            new IndexedUrl(23, "https://www.servemanager.com/blog/3101/efiling-with-servemanager"),
            new IndexedUrl(24, "https://www.alncorp.com/"),
            new IndexedUrl(25, "https://www.shelbycountytn.gov/2524/About-E-Filing"),
            new IndexedUrl(26, "https://www.sage.com/africa/news/press-releases/2021/07/new-innovative-sars-efiling-integration-from-sage-eases-compliance-for-accountants/"),
            new IndexedUrl(27, "https://www.business-standard.com/article/finance/kotak-mahindra-bank-completes-integration-for-direct-tax-payments-122071401354_1.html"),
            new IndexedUrl(28, "https://www.irs.gov/payments/pay-by-debit-or-credit-card-when-you-e-file"),
            new IndexedUrl(29, "https://api.sap.com/package/eFilingofEmployeesPaymentsandDeductions202021UnitedKingdom"),
            new IndexedUrl(30, "https://www.nccourts.gov/ecourts"),
            new IndexedUrl(31, "https://www.tybera.com/"),
            new IndexedUrl(32, "https://www.courts.mo.gov/page.jsp?id=49113"),
            new IndexedUrl(33, "https://www.revisor.mn.gov/court_rules/gp/id/14/"),
            new IndexedUrl(34, "https://www.dallascounty.org/government/jpcourts/4-1/electronic-filing.php"),
            new IndexedUrl(35, "https://cic.countyofkane.org/how-to-efile"),
            new IndexedUrl(36, "http://www.courtswv.gov/e-file/rules.html"),
            new IndexedUrl(37, "https://www.courts.wa.gov/jis/?fa=jis.ITGRequestDetail&requestID=291"),
            new IndexedUrl(38, "https://www.fileandservexpress.com/"),
            new IndexedUrl(39, "https://www.nnva.gov/204/E-Filing"),
            new IndexedUrl(40, "https://miottawa.org/Departments/CountyClerk/CourtRecords/efiling.htm"),
            new IndexedUrl(41, "https://www.mass.gov/doc/e-filing/download"),
            new IndexedUrl(42, "https://www.ncsc.org/__data/assets/pdf_file/0022/18490/efiling-issues-paper-v-101-final.pdf"),
            new IndexedUrl(43, "https://www.rsi.com/state-judicial-solutions/electronic-court-filing/"),
            new IndexedUrl(44, "https://www.aatrix.com/"),
            new IndexedUrl(45, "https://www.fec.gov/about/reports-about-fec/agency-operations/e-filing-study-2016/"),
            new IndexedUrl(46, "https://rapidlegal.com/exploring-stakeholders-in-the-california-court-efiling-workflow/"),
            new IndexedUrl(47, "https://www.csitech.com/justice-courts/courts-efiling/"),
            new IndexedUrl(48, "https://www.champaigncircuitclerk.org/common-forms/electronic-filing/"),
            new IndexedUrl(49, "https://www.epcounty.com/efile.htm"),
            new IndexedUrl(50, "https://www.txdocs.com/products/new-txdocs-efiling/"),
            new IndexedUrl(51, "https://leg.colorado.gov/audits/judicial-departments-integrated-colorado-courts-e-filing-and-judicial-paper-demand-systems"),
            new IndexedUrl(52, "https://www.ricoh-usa.com/-/media/Ricoh/Common/PDFs/Brochures/Software/R4117_Ricoh_SI_Legal_brochure.pdf"),
            new IndexedUrl(53, "https://www.courts.state.wy.us/supreme-court/clerk-of-court-efiling/efiling/"),
            new IndexedUrl(54, "https://www.tarrantcounty.com/content/dam/main/district-clerk/Efiling_Frequently_Asked_Questions.pdf"),
            new IndexedUrl(55, "https://www.lehighcounty.org/departments/clerk-of-judicial-records/civil-division/attorney-docket-access/e-filing"),
            new IndexedUrl(56, "https://www.co.madison.il.us/departments/circuit_clerk/e-file/index.php"),
            new IndexedUrl(57, "https://imagesoftinc.com/allblogposts/integrating-efiling-with-the-case-management-system/"),
            new IndexedUrl(58, "https://www.cantonrep.com/story/news/local/stark-county/2022/07/11/stark-court-officials-update-commissioners-e-filing-project/10029971002/"),
            new IndexedUrl(59, "https://www.ferc.gov/sites/default/files/2020-04/efilingdocumentlist.pdf"),
            new IndexedUrl(60, "https://www.nelcosolutions.com/electronic-filing-services/"),
            new IndexedUrl(61, "https://www.utcourts.gov/efiling/docs/Electronic_Filing_Guide.pdf"),
            new IndexedUrl(62, "https://lasallecounty.com/efiling"),
            new IndexedUrl(63, "https://legaldocumentserver.com/2022/03/28/does-contra-costa-county-have-efiling/"),
            new IndexedUrl(64, "https://www.efilecabinet.com/"),
            new IndexedUrl(65, "https://www.leg.state.nv.us/courtrules/NEFCR.html"),
            new IndexedUrl(66, "https://truefiling.com/"),
            new IndexedUrl(67, "https://iqsworks.com/2020/12/iqs-expands-e-filing-integration-across-new-york/"),
            new IndexedUrl(68, "http://mdcourts.gov/mdec/pdfs/efilingfactsheet.pdf"),
            new IndexedUrl(69, "https://www.practicepanther.com/integrations/jubilee"),
            new IndexedUrl(70, "https://www.co.benton.wa.us/pview.aspx?id=21053&catid=0"),
            new IndexedUrl(71, "http://www.flclerks.com/resource/resmgr/Files/E-Filing_Authority.pdf"),
            new IndexedUrl(72, "https://www.nycourts.gov/LegacyPDFS/RULES/efiling/PDF/16_E-file_Report.pdf"),
            new IndexedUrl(73, "https://www.pbgc.gov/prac/prem/filings/e-filing-resources"),
            new IndexedUrl(74, "https://www.cc-courts.org/efiling/docs/EFilingOverview.pdf"),
            new IndexedUrl(75, "https://www.txcourts.gov/media/166698/eFilingFinalAgreement11-7-12.pdf"),
            new IndexedUrl(76, "http://www.lacourt.org/division/efiling/pdf/ComplexefilingFAQs.pdf"),
            new IndexedUrl(77, "https://www.taxwaresystems.com/"),
            new IndexedUrl(78, "https://www.mahoningcountyoh.gov/182/Clerk-of-Courts"),
            new IndexedUrl(79, "https://casetext.com/rule/minnesota-court-rules/minnesota-general-rules-of-practice/title-i-rules-applicable-to-all-court-proceedings/rule-14-e-filing-and-e-service/rule-1401-mandatory-and-voluntary-e-file-and-e-service"),
            new IndexedUrl(80, "https://www.netdocuments.com/blog/which-parts-of-court-filing-can-be-automated"),
            new IndexedUrl(81, "https://www.xero.com/blog/2020/12/xero-sars-integration-vat-efiling/"),
            new IndexedUrl(82, "http://sage100contractorhelp.sagecre.com/help/sage100contractor/US/19_7/Content/Modules/5-Payroll/About_Sage_100_Contractor_integration_with_Aatrix.htm"),
            new IndexedUrl(83, "https://www.wicourts.gov/ecourts/efilecircuit/docs/eFilingrule.pdf"),
            new IndexedUrl(84, "https://www.bill.com/app-marketplace/tax1099com-integration"),
            new IndexedUrl(85, "https://www.efilemadeeasy.com/about-us/"),
            new IndexedUrl(86, "https://practicehwy.com/efiling.html"),
            new IndexedUrl(87, "https://www.incometax.gov.in/iec/foportal/help/my-bank-account-faq"),
            new IndexedUrl(88, "https://apps.nlrb.gov/myAccount/assets/E-Filing-System-User-Guide.pdf"),
            new IndexedUrl(89, "https://desotoparishclerk.org/divisions/e-filing/"),
            new IndexedUrl(90, "https://researchil.tylerhost.net/CourtRecordsSearch"),
            new IndexedUrl(91, "https://chanceryclerkandmaster.nashville.gov/electronic-case-filing/"),
            new IndexedUrl(92, "https://www.abclegal.com/blog/between-the-lines-e-filing-with-abc-legal"),
            new IndexedUrl(93, "https://efiling.clerkofcourt.maricopa.gov/help.aspx"),
            new IndexedUrl(94, "https://www.lsc.gov/sites/default/files/Best-Pratices.pdf"),
            new IndexedUrl(95, "https://researchil.tylerhost.net/CourtRecordsSearch"),
            new IndexedUrl(96, "https://chanceryclerkandmaster.nashville.gov/electronic-case-filing/"),
            new IndexedUrl(97, "https://www.abclegal.com/blog/between-the-lines-e-filing-with-abc-legal"),
            new IndexedUrl(98, "https://efiling.clerkofcourt.maricopa.gov/help.aspx"),
            new IndexedUrl(99, "https://www.lsc.gov/sites/default/files/Best-Pratices.pdf"),
        });
    }
}
