namespace InfoTrack.GoogleRank.Services;

public class HardCodedHtmlScraper : IHtmlScraper
{
    public Task<object[]> SelectElementsWithCssSelector(Stream stream, ILogger logger)
    {
        return Task.FromResult(new object[]
        {
            new { index = 0, HRefValue = "https://www.g2.com/categories/e-filing" },
            new { index = 1, HRefValue = "https://imanage.com/partner-products/partner-product/?productId=481" },
            new { index = 2, HRefValue = "http://efile.illinoiscourts.gov/service-providers.htm" },
            new { index = 3, HRefValue = "https://www.leap.us/integrations/e-filing-infotrack/" },
            new { index = 4, HRefValue = "https://www.gsccca.org/learn/efiling-information/vendor-integration" },
            new { index = 5, HRefValue = "https://www.jbits.courts.state.co.us/efiling/web/login.htm" },
            new { index = 6, HRefValue = "/search?num=100&sxsrf=ALiCzsZljppeRSXkLdyF3ib_x3S0HPwGIw:1661778798894&q=efiling+%22integration%22&sa=X&ved=2ahUKEwjaiYO4kOz5AhVDkYkEHZJyDRIQ5t4CegUIzwEQAQ" },
            new { index = 7, HRefValue = "https://www.efiletexas.gov/Service-Providers/1eFile.htm" },
            new { index = 8, HRefValue = "https://www.clio.com/app-directory/infotrack/" },
            new { index = 9, HRefValue = "https://www.cms.gov/Regulations-and-Guidance/Review-Boards/PRRBReview/Electronic-Filing" },
            new { index = 10, HRefValue = "https://www.onelegal.com/blog/defining-integrated-efiling-the-next-phase-of-innovation/" },
            new { index = 11, HRefValue = "https://www.wipo.int/madrid/en/how_to/efile/" },
            new { index = 12, HRefValue = "https://efile.dol.gov/" },
            new { index = 13, HRefValue = "https://uslegalpro.com/pg/court-efiling-automation" },
            new { index = 14, HRefValue = "https://www.smokeball.com/features/legal-efiling-electronic-signatures/" },
            new { index = 15, HRefValue = "https://www.mncourts.gov/mncourtsgov/media/IntegrationServices/IntegratedeFilingServicesFastFacts.pdf" },
            new { index = 16, HRefValue = "https://www.courts.ca.gov/partners/techoverview.htm" },
            new { index = 17, HRefValue = "https://www.efilingportal.com/" },
            new { index = 18, HRefValue = "https://www.tax1099.com/integrations" },
            new { index = 19, HRefValue = "https://www.in.gov/courts/efiling/how-it-works/" },
            new { index = 20, HRefValue = "https://www.hidalgocounty.us/208/e-Filing" },
            new { index = 21, HRefValue = "https://mixnet.com/e-recording-and-efiling-integration-with-land-records-indexing-management/" },
            new { index = 22, HRefValue = "https://www.uscourts.gov/court-records/electronic-filing-cmecf" },
            new { index = 23, HRefValue = "https://www.servemanager.com/blog/3101/efiling-with-servemanager" },
            new { index = 24, HRefValue = "https://www.alncorp.com/" },
            new { index = 25, HRefValue = "https://www.shelbycountytn.gov/2524/About-E-Filing" },
            new { index = 26, HRefValue = "https://www.sage.com/africa/news/press-releases/2021/07/new-innovative-sars-efiling-integration-from-sage-eases-compliance-for-accountants/" },
            new { index = 27, HRefValue = "https://www.business-standard.com/article/finance/kotak-mahindra-bank-completes-integration-for-direct-tax-payments-122071401354_1.html" },
            new { index = 28, HRefValue = "https://www.irs.gov/payments/pay-by-debit-or-credit-card-when-you-e-file" },
            new { index = 29, HRefValue = "https://api.sap.com/package/eFilingofEmployeesPaymentsandDeductions202021UnitedKingdom" },
            new { index = 30, HRefValue = "https://www.nccourts.gov/ecourts" },
            new { index = 31, HRefValue = "https://www.tybera.com/" },
            new { index = 32, HRefValue = "https://www.courts.mo.gov/page.jsp?id=49113" },
            new { index = 33, HRefValue = "https://www.revisor.mn.gov/court_rules/gp/id/14/" },
            new { index = 34, HRefValue = "https://www.dallascounty.org/government/jpcourts/4-1/electronic-filing.php" },
            new { index = 35, HRefValue = "https://cic.countyofkane.org/how-to-efile" },
            new { index = 36, HRefValue = "http://www.courtswv.gov/e-file/rules.html" },
            new { index = 37, HRefValue = "https://www.courts.wa.gov/jis/?fa=jis.ITGRequestDetail&requestID=291" },
            new { index = 38, HRefValue = "https://www.fileandservexpress.com/" },
            new { index = 39, HRefValue = "https://www.nnva.gov/204/E-Filing" },
            new { index = 40, HRefValue = "https://miottawa.org/Departments/CountyClerk/CourtRecords/efiling.htm" },
            new { index = 41, HRefValue = "https://www.mass.gov/doc/e-filing/download" },
            new { index = 42, HRefValue = "https://www.ncsc.org/__data/assets/pdf_file/0022/18490/efiling-issues-paper-v-101-final.pdf" },
            new { index = 43, HRefValue = "https://www.rsi.com/state-judicial-solutions/electronic-court-filing/" },
            new { index = 44, HRefValue = "https://www.aatrix.com/" },
            new { index = 45, HRefValue = "https://www.fec.gov/about/reports-about-fec/agency-operations/e-filing-study-2016/" },
            new { index = 46, HRefValue = "https://rapidlegal.com/exploring-stakeholders-in-the-california-court-efiling-workflow/" },
            new { index = 47, HRefValue = "https://www.csitech.com/justice-courts/courts-efiling/" },
            new { index = 48, HRefValue = "https://www.champaigncircuitclerk.org/common-forms/electronic-filing/" },
            new { index = 49, HRefValue = "https://www.epcounty.com/efile.htm" },
            new { index = 50, HRefValue = "https://www.txdocs.com/products/new-txdocs-efiling/" },
            new { index = 51, HRefValue = "https://leg.colorado.gov/audits/judicial-departments-integrated-colorado-courts-e-filing-and-judicial-paper-demand-systems" },
            new { index = 52, HRefValue = "https://www.ricoh-usa.com/-/media/Ricoh/Common/PDFs/Brochures/Software/R4117_Ricoh_SI_Legal_brochure.pdf" },
            new { index = 53, HRefValue = "https://www.courts.state.wy.us/supreme-court/clerk-of-court-efiling/efiling/" },
            new { index = 54, HRefValue = "https://www.tarrantcounty.com/content/dam/main/district-clerk/Efiling_Frequently_Asked_Questions.pdf" },
            new { index = 55, HRefValue = "https://www.lehighcounty.org/departments/clerk-of-judicial-records/civil-division/attorney-docket-access/e-filing" },
            new { index = 56, HRefValue = "https://www.co.madison.il.us/departments/circuit_clerk/e-file/index.php" },
            new { index = 57, HRefValue = "https://imagesoftinc.com/allblogposts/integrating-efiling-with-the-case-management-system/" },
            new { index = 58, HRefValue = "https://www.cantonrep.com/story/news/local/stark-county/2022/07/11/stark-court-officials-update-commissioners-e-filing-project/10029971002/" },
            new { index = 59, HRefValue = "https://www.ferc.gov/sites/default/files/2020-04/efilingdocumentlist.pdf" },
            new { index = 60, HRefValue = "https://www.nelcosolutions.com/electronic-filing-services/" },
            new { index = 61, HRefValue = "https://www.utcourts.gov/efiling/docs/Electronic_Filing_Guide.pdf" },
            new { index = 62, HRefValue = "https://lasallecounty.com/efiling" },
            new { index = 63, HRefValue = "https://legaldocumentserver.com/2022/03/28/does-contra-costa-county-have-efiling/" },
            new { index = 64, HRefValue = "https://www.efilecabinet.com/" },
            new { index = 65, HRefValue = "https://www.leg.state.nv.us/courtrules/NEFCR.html" },
            new { index = 66, HRefValue = "https://truefiling.com/" },
            new { index = 67, HRefValue = "https://iqsworks.com/2020/12/iqs-expands-e-filing-integration-across-new-york/" },
            new { index = 68, HRefValue = "http://mdcourts.gov/mdec/pdfs/efilingfactsheet.pdf" },
            new { index = 69, HRefValue = "https://www.practicepanther.com/integrations/jubilee" },
            new { index = 70, HRefValue = "https://www.co.benton.wa.us/pview.aspx?id=21053&catid=0" },
            new { index = 71, HRefValue = "http://www.flclerks.com/resource/resmgr/Files/E-Filing_Authority.pdf" },
            new { index = 72, HRefValue = "https://www.nycourts.gov/LegacyPDFS/RULES/efiling/PDF/16_E-file_Report.pdf" },
            new { index = 73, HRefValue = "https://www.pbgc.gov/prac/prem/filings/e-filing-resources" },
            new { index = 74, HRefValue = "https://www.cc-courts.org/efiling/docs/EFilingOverview.pdf" },
            new { index = 75, HRefValue = "https://www.txcourts.gov/media/166698/eFilingFinalAgreement11-7-12.pdf" },
            new { index = 76, HRefValue = "http://www.lacourt.org/division/efiling/pdf/ComplexefilingFAQs.pdf" },
            new { index = 77, HRefValue = "https://www.taxwaresystems.com/" },
            new { index = 78, HRefValue = "https://www.mahoningcountyoh.gov/182/Clerk-of-Courts" },
            new { index = 79, HRefValue = "https://casetext.com/rule/minnesota-court-rules/minnesota-general-rules-of-practice/title-i-rules-applicable-to-all-court-proceedings/rule-14-e-filing-and-e-service/rule-1401-mandatory-and-voluntary-e-file-and-e-service" },
            new { index = 80, HRefValue = "https://www.netdocuments.com/blog/which-parts-of-court-filing-can-be-automated" },
            new { index = 81, HRefValue = "https://www.xero.com/blog/2020/12/xero-sars-integration-vat-efiling/" },
            new { index = 82, HRefValue = "http://sage100contractorhelp.sagecre.com/help/sage100contractor/US/19_7/Content/Modules/5-Payroll/About_Sage_100_Contractor_integration_with_Aatrix.htm" },
            new { index = 83, HRefValue = "https://www.wicourts.gov/ecourts/efilecircuit/docs/eFilingrule.pdf" },
            new { index = 84, HRefValue = "https://www.bill.com/app-marketplace/tax1099com-integration" },
            new { index = 85, HRefValue = "https://www.efilemadeeasy.com/about-us/" },
            new { index = 86, HRefValue = "https://practicehwy.com/efiling.html" },
            new { index = 87, HRefValue = "https://www.incometax.gov.in/iec/foportal/help/my-bank-account-faq" },
            new { index = 88, HRefValue = "https://apps.nlrb.gov/myAccount/assets/E-Filing-System-User-Guide.pdf" },
            new { index = 89, HRefValue = "https://desotoparishclerk.org/divisions/e-filing/" },
            new { index = 90, HRefValue = "https://researchil.tylerhost.net/CourtRecordsSearch" },
            new { index = 91, HRefValue = "https://chanceryclerkandmaster.nashville.gov/electronic-case-filing/" },
            new { index = 92, HRefValue = "https://www.abclegal.com/blog/between-the-lines-e-filing-with-abc-legal" },
            new { index = 93, HRefValue = "https://efiling.clerkofcourt.maricopa.gov/help.aspx" },
            new { index = 94, HRefValue = "https://www.lsc.gov/sites/default/files/Best-Pratices.pdf" },
            new { index = 95, HRefValue = "https://researchil.tylerhost.net/CourtRecordsSearch" },
            new { index = 96, HRefValue = "https://chanceryclerkandmaster.nashville.gov/electronic-case-filing/" },
            new { index = 97, HRefValue = "https://www.abclegal.com/blog/between-the-lines-e-filing-with-abc-legal" },
            new { index = 98, HRefValue = "https://efiling.clerkofcourt.maricopa.gov/help.aspx" },
            new { index = 99, HRefValue = "https://www.lsc.gov/sites/default/files/Best-Pratices.pdf" }
        });
    }
}
